export const FINANCIAL_PRODUCTS = [
  {
    product_id: "PROD_1",
    category: "Credit Card",
    subcategory: "Basic",
    tier: "Entry",
    name: "Entry Basic Credit Card",
    description: "entry level basic credit card product.",
    risk_customer: 2,
    value_customer: 2,
    profit_margin: 3,
    risk_bank: 2,
    retention_value: 1,
    details: {
      interest_rate: 21.99,
      annual_fee: 0,
      credit_limit: 1000,
      rewards_rate: 1.0,
    },
  },
  {
    product_id: "PROD_2",
    category: "Credit Card",
    subcategory: "Basic",
    tier: "Standard",
    name: "Standard Basic Credit Card",
    description: "standard level basic credit card product.",
    risk_customer: 2,
    value_customer: 3,
    profit_margin: 4,
    risk_bank: 2,
    retention_value: 2,
    details: {
      interest_rate: 19.99,
      annual_fee: 25,
      credit_limit: 2500,
      rewards_rate: 1.5,
    },
  },
  {
    product_id: "PROD_3",
    category: "Credit Card",
    subcategory: "Basic",
    tier: "Premium",
    name: "Premium Basic Credit Card",
    description: "premium level basic credit card product.",
    risk_customer: 2,
    value_customer: 4,
    profit_margin: 5,
    risk_bank: 2,
    retention_value: 3,
    details: {
      interest_rate: 18.99,
      annual_fee: 50,
      credit_limit: 5000,
      rewards_rate: 2.0,
    },
  },
  {
    product_id: "PROD_4",
    category: "Credit Card",
    subcategory: "Basic",
    tier: "Elite",
    name: "Elite Basic Credit Card",
    description: "elite level basic credit card product.",
    risk_customer: 3,
    value_customer: 5,
    profit_margin: 6,
    risk_bank: 2,
    retention_value: 3,
    details: {
      interest_rate: 17.99,
      annual_fee: 75,
      credit_limit: 7500,
      rewards_rate: 2.5,
    },
  },
  {
    product_id: "PROD_5",
    category: "Credit Card",
    subcategory: "Gold",
    tier: "Entry",
    name: "Entry Gold Credit Card",
    description: "entry level gold credit card product.",
    risk_customer: 2,
    value_customer: 4,
    profit_margin: 3,
    risk_bank: 2,
    retention_value: 4,
    details: {
      interest_rate: 19.99,
      annual_fee: 50,
      credit_limit: 5000,
      rewards_rate: 1.5,
    },
  },
  {
    product_id: "PROD_6",
    category: "Credit Card",
    subcategory: "Gold",
    tier: "Standard",
    name: "Standard Gold Credit Card",
    description: "standard level gold credit card product.",
    risk_customer: 3,
    value_customer: 5,
    profit_margin: 4,
    risk_bank: 2,
    retention_value: 5,
    details: {
      interest_rate: 18.99,
      annual_fee: 95,
      credit_limit: 10000,
      rewards_rate: 2.0,
    },
  },
  {
    product_id: "PROD_7",
    category: "Credit Card",
    subcategory: "Gold",
    tier: "Premium",
    name: "Premium Gold Credit Card",
    description: "premium level gold credit card product.",
    risk_customer: 4,
    value_customer: 6,
    profit_margin: 5,
    risk_bank: 2,
    retention_value: 6,
    details: {
      interest_rate: 17.99,
      annual_fee: 150,
      credit_limit: 15000,
      rewards_rate: 2.5,
    },
  },
  {
    product_id: "PROD_8",
    category: "Credit Card",
    subcategory: "Gold",
    tier: "Elite",
    name: "Elite Gold Credit Card",
    description: "elite level gold credit card product.",
    risk_customer: 4,
    value_customer: 8,
    profit_margin: 6,
    risk_bank: 2,
    retention_value: 8,
    details: {
      interest_rate: 16.99,
      annual_fee: 195,
      credit_limit: 20000,
      rewards_rate: 3.0,
    },
  },
  {
    product_id: "PROD_9",
    category: "Credit Card",
    subcategory: "Platinum",
    tier: "Entry",
    name: "Entry Platinum Credit Card",
    description: "entry level platinum credit card product.",
    risk_customer: 3,
    value_customer: 5,
    profit_margin: 6,
    risk_bank: 5,
    retention_value: 4,
    details: {
      interest_rate: 18.99,
      annual_fee: 95,
      credit_limit: 10000,
      rewards_rate: 2.0,
    },
  },
  {
    product_id: "PROD_10",
    category: "Credit Card",
    subcategory: "Platinum",
    tier: "Standard",
    name: "Standard Platinum Credit Card",
    description: "standard level platinum credit card product.",
    risk_customer: 4,
    value_customer: 7,
    profit_margin: 7,
    risk_bank: 4,
    retention_value: 6,
    details: {
      interest_rate: 17.99,
      annual_fee: 195,
      credit_limit: 20000,
      rewards_rate: 2.5,
    },
  },
  {
    product_id: "PROD_11",
    category: "Credit Card",
    subcategory: "Platinum",
    tier: "Premium",
    name: "Premium Platinum Credit Card",
    description: "premium level platinum credit card product.",
    risk_customer: 5,
    value_customer: 9,
    profit_margin: 8,
    risk_bank: 4,
    retention_value: 8,
    details: {
      interest_rate: 16.99,
      annual_fee: 295,
      credit_limit: 30000,
      rewards_rate: 3.0,
    },
  },
  {
    product_id: "PROD_12",
    category: "Credit Card",
    subcategory: "Platinum",
    tier: "Elite",
    name: "Elite Platinum Credit Card",
    description: "elite level platinum credit card product.",
    risk_customer: 6,
    value_customer: 10,
    profit_margin: 10,
    risk_bank: 3,
    retention_value: 10,
    details: {
      interest_rate: 15.99,
      annual_fee: 395,
      credit_limit: 50000,
      rewards_rate: 4.0,
    },
  },
  {
    product_id: "PROD_13",
    category: "Credit Card",
    subcategory: "Business",
    tier: "Entry",
    name: "Entry Business Credit Card",
    description: "entry level business credit card product.",
    risk_customer: 6,
    value_customer: 5,
    profit_margin: 6,
    risk_bank: 10,
    retention_value: 4,
    details: {
      interest_rate: 18.99,
      annual_fee: 75,
      credit_limit: 5000,
      rewards_rate: 1.5,
    },
  },
  {
    product_id: "PROD_14",
    category: "Credit Card",
    subcategory: "Business",
    tier: "Standard",
    name: "Standard Business Credit Card",
    description: "standard level business credit card product.",
    risk_customer: 8,
    value_customer: 7,
    profit_margin: 8,
    risk_bank: 9,
    retention_value: 6,
    details: {
      interest_rate: 17.99,
      annual_fee: 125,
      credit_limit: 15000,
      rewards_rate: 2.0,
    },
  },
  {
    product_id: "PROD_15",
    category: "Credit Card",
    subcategory: "Business",
    tier: "Premium",
    name: "Premium Business Credit Card",
    description: "premium level business credit card product.",
    risk_customer: 10,
    value_customer: 9,
    profit_margin: 10,
    risk_bank: 8,
    retention_value: 8,
    details: {
      interest_rate: 16.99,
      annual_fee: 195,
      credit_limit: 25000,
      rewards_rate: 2.5,
    },
  },
  {
    product_id: "PROD_16",
    category: "Credit Card",
    subcategory: "Business",
    tier: "Elite",
    name: "Elite Business Credit Card",
    description: "elite level business credit card product.",
    risk_customer: 10,
    value_customer: 10,
    profit_margin: 10,
    risk_bank: 7,
    retention_value: 10,
    details: {
      interest_rate: 15.99,
      annual_fee: 295,
      credit_limit: 50000,
      rewards_rate: 3.0,
    },
  },
  {
    product_id: "PROD_17",
    category: "Credit Card",
    subcategory: "Student",
    tier: "Entry",
    name: "Entry Student Credit Card",
    description: "entry level student credit card product.",
    risk_customer: 3,
    value_customer: 2,
    profit_margin: 2,
    risk_bank: 7,
    retention_value: 4,
    details: {
      interest_rate: 19.99,
      annual_fee: 0,
      credit_limit: 500,
      rewards_rate: 1.0,
    },
  },
  {
    product_id: "PROD_18",
    category: "Credit Card",
    subcategory: "Student",
    tier: "Standard",
    name: "Standard Student Credit Card",
    description: "standard level student credit card product.",
    risk_customer: 4,
    value_customer: 3,
    profit_margin: 3,
    risk_bank: 6,
    retention_value: 5,
    details: {
      interest_rate: 18.99,
      annual_fee: 0,
      credit_limit: 1000,
      rewards_rate: 1.25,
    },
  },
  {
    product_id: "PROD_19",
    category: "Credit Card",
    subcategory: "Student",
    tier: "Premium",
    name: "Premium Student Credit Card",
    description: "premium level student credit card product.",
    risk_customer: 5,
    value_customer: 4,
    profit_margin: 4,
    risk_bank: 5,
    retention_value: 6,
    details: {
      interest_rate: 17.99,
      annual_fee: 25,
      credit_limit: 1500,
      rewards_rate: 1.5,
    },
  },
  {
    product_id: "PROD_20",
    category: "Credit Card",
    subcategory: "Student",
    tier: "Elite",
    name: "Elite Student Credit Card",
    description: "elite level student credit card product.",
    risk_customer: 6,
    value_customer: 5,
    profit_margin: 4,
    risk_bank: 5,
    retention_value: 8,
    details: {
      interest_rate: 16.99,
      annual_fee: 45,
      credit_limit: 2500,
      rewards_rate: 2.0,
    },
  },
  {
    product_id: "PROD_21",
    category: "Credit Card",
    subcategory: "Travel",
    tier: "Entry",
    name: "Entry Travel Credit Card",
    description: "entry level travel credit card product.",
    risk_customer: 3,
    value_customer: 4,
    profit_margin: 6,
    risk_bank: 4,
    retention_value: 2,
    details: {
      interest_rate: 20.99,
      annual_fee: 75,
      credit_limit: 3000,
      rewards_rate: 2.0,
    },
  },
  {
    product_id: "PROD_22",
    category: "Credit Card",
    subcategory: "Travel",
    tier: "Standard",
    name: "Standard Travel Credit Card",
    description: "standard level travel credit card product.",
    risk_customer: 4,
    value_customer: 5,
    profit_margin: 7,
    risk_bank: 3,
    retention_value: 3,
    details: {
      interest_rate: 19.99,
      annual_fee: 150,
      credit_limit: 7500,
      rewards_rate: 3.0,
    },
  },
  {
    product_id: "PROD_23",
    category: "Credit Card",
    subcategory: "Travel",
    tier: "Premium",
    name: "Premium Travel Credit Card",
    description: "premium level travel credit card product.",
    risk_customer: 5,
    value_customer: 6,
    profit_margin: 8,
    risk_bank: 3,
    retention_value: 4,
    details: {
      interest_rate: 18.99,
      annual_fee: 250,
      credit_limit: 15000,
      rewards_rate: 4.0,
    },
  },
  {
    product_id: "PROD_24",
    category: "Credit Card",
    subcategory: "Travel",
    tier: "Elite",
    name: "Elite Travel Credit Card",
    description: "elite level travel credit card product.",
    risk_customer: 6,
    value_customer: 8,
    profit_margin: 10,
    risk_bank: 2,
    retention_value: 5,
    details: {
      interest_rate: 17.99,
      annual_fee: 350,
      credit_limit: 25000,
      rewards_rate: 5.0,
    },
  },
  {
    product_id: "PROD_25",
    category: "Credit Card",
    subcategory: "Dining",
    tier: "Entry",
    name: "Entry Dining Credit Card",
    description: "entry level dining credit card product.",
    risk_customer: 2,
    value_customer: 4,
    profit_margin: 3,
    risk_bank: 2,
    retention_value: 3,
    details: {
      interest_rate: 20.99,
      annual_fee: 50,
      credit_limit: 2000,
      rewards_rate: 3.0,
    },
  },
  {
    product_id: "PROD_26",
    category: "Credit Card",
    subcategory: "Dining",
    tier: "Standard",
    name: "Standard Dining Credit Card",
    description: "standard level dining credit card product.",
    risk_customer: 2,
    value_customer: 5,
    profit_margin: 4,
    risk_bank: 2,
    retention_value: 4,
    details: {
      interest_rate: 19.99,
      annual_fee: 95,
      credit_limit: 5000,
      rewards_rate: 4.0,
    },
  },
  {
    product_id: "PROD_27",
    category: "Credit Card",
    subcategory: "Dining",
    tier: "Premium",
    name: "Premium Dining Credit Card",
    description: "premium level dining credit card product.",
    risk_customer: 2,
    value_customer: 6,
    profit_margin: 5,
    risk_bank: 2,
    retention_value: 5,
    details: {
      interest_rate: 18.99,
      annual_fee: 150,
      credit_limit: 10000,
      rewards_rate: 5.0,
    },
  },
  {
    product_id: "PROD_28",
    category: "Credit Card",
    subcategory: "Dining",
    tier: "Elite",
    name: "Elite Dining Credit Card",
    description: "elite level dining credit card product.",
    risk_customer: 3,
    value_customer: 8,
    profit_margin: 6,
    risk_bank: 2,
    retention_value: 6,
    details: {
      interest_rate: 17.99,
      annual_fee: 195,
      credit_limit: 15000,
      rewards_rate: 6.0,
    },
  },
  {
    product_id: "PROD_29",
    category: "Credit Card",
    subcategory: "Amazon",
    tier: "Entry",
    name: "Entry Amazon Credit Card",
    description: "entry level amazon credit card product.",
    risk_customer: 2,
    value_customer: 4,
    profit_margin: 4,
    risk_bank: 2,
    retention_value: 4,
    details: {
      interest_rate: 20.99,
      annual_fee: 0,
      credit_limit: 1500,
      rewards_rate: 3.0,
    },
  },
  {
    product_id: "PROD_30",
    category: "Credit Card",
    subcategory: "Amazon",
    tier: "Standard",
    name: "Standard Amazon Credit Card",
    description: "standard level amazon credit card product.",
    risk_customer: 2,
    value_customer: 5,
    profit_margin: 5,
    risk_bank: 2,
    retention_value: 5,
    details: {
      interest_rate: 19.99,
      annual_fee: 49,
      credit_limit: 3000,
      rewards_rate: 4.0,
    },
  },
  {
    product_id: "PROD_31",
    category: "Credit Card",
    subcategory: "Amazon",
    tier: "Premium",
    name: "Premium Amazon Credit Card",
    description: "premium level amazon credit card product.",
    risk_customer: 2,
    value_customer: 6,
    profit_margin: 6,
    risk_bank: 2,
    retention_value: 6,
    details: {
      interest_rate: 18.99,
      annual_fee: 99,
      credit_limit: 6000,
      rewards_rate: 5.0,
    },
  },
  {
    product_id: "PROD_32",
    category: "Credit Card",
    subcategory: "Amazon",
    tier: "Elite",
    name: "Elite Amazon Credit Card",
    description: "elite level amazon credit card product.",
    risk_customer: 3,
    value_customer: 8,
    profit_margin: 7,
    risk_bank: 2,
    retention_value: 8,
    details: {
      interest_rate: 17.99,
      annual_fee: 149,
      credit_limit: 10000,
      rewards_rate: 6.0,
    },
  },
  {
    product_id: "PROD_33",
    category: "Credit Card",
    subcategory: "Fuel",
    tier: "Entry",
    name: "Entry Fuel Credit Card",
    description: "entry level fuel credit card product.",
    risk_customer: 2,
    value_customer: 4,
    profit_margin: 3,
    risk_bank: 2,
    retention_value: 2,
    details: {
      interest_rate: 21.99,
      annual_fee: 25,
      credit_limit: 1500,
      rewards_rate: 3.0,
    },
  },
  {
    product_id: "PROD_34",
    category: "Credit Card",
    subcategory: "Fuel",
    tier: "Standard",
    name: "Standard Fuel Credit Card",
    description: "standard level fuel credit card product.",
    risk_customer: 2,
    value_customer: 5,
    profit_margin: 4,
    risk_bank: 2,
    retention_value: 3,
    details: {
      interest_rate: 20.99,
      annual_fee: 50,
      credit_limit: 3000,
      rewards_rate: 4.0,
    },
  },
  {
    product_id: "PROD_35",
    category: "Credit Card",
    subcategory: "Fuel",
    tier: "Premium",
    name: "Premium Fuel Credit Card",
    description: "premium level fuel credit card product.",
    risk_customer: 2,
    value_customer: 6,
    profit_margin: 5,
    risk_bank: 2,
    retention_value: 4,
    details: {
      interest_rate: 19.99,
      annual_fee: 95,
      credit_limit: 5000,
      rewards_rate: 5.0,
    },
  },
  {
    product_id: "PROD_36",
    category: "Credit Card",
    subcategory: "Fuel",
    tier: "Elite",
    name: "Elite Fuel Credit Card",
    description: "elite level fuel credit card product.",
    risk_customer: 3,
    value_customer: 8,
    profit_margin: 6,
    risk_bank: 2,
    retention_value: 5,
    details: {
      interest_rate: 18.99,
      annual_fee: 145,
      credit_limit: 7500,
      rewards_rate: 6.0,
    },
  },
  {
    product_id: "PROD_37",
    category: "Credit Card",
    subcategory: "Luxury",
    tier: "Entry",
    name: "Entry Luxury Credit Card",
    description: "entry level luxury credit card product.",
    risk_customer: 4,
    value_customer: 6,
    profit_margin: 7,
    risk_bank: 5,
    retention_value: 5,
    details: {
      interest_rate: 17.99,
      annual_fee: 195,
      credit_limit: 10000,
      rewards_rate: 2.5,
    },
  },
  {
    product_id: "PROD_38",
    category: "Credit Card",
    subcategory: "Luxury",
    tier: "Standard",
    name: "Standard Luxury Credit Card",
    description: "standard level luxury credit card product.",
    risk_customer: 5,
    value_customer: 8,
    profit_margin: 9,
    risk_bank: 4,
    retention_value: 7,
    details: {
      interest_rate: 16.99,
      annual_fee: 295,
      credit_limit: 25000,
      rewards_rate: 3.5,
    },
  },
  {
    product_id: "PROD_39",
    category: "Credit Card",
    subcategory: "Luxury",
    tier: "Premium",
    name: "Premium Luxury Credit Card",
    description: "premium level luxury credit card product.",
    risk_customer: 6,
    value_customer: 10,
    profit_margin: 10,
    risk_bank: 4,
    retention_value: 9,
    details: {
      interest_rate: 15.99,
      annual_fee: 495,
      credit_limit: 50000,
      rewards_rate: 4.5,
    },
  },
  {
    product_id: "PROD_40",
    category: "Credit Card",
    subcategory: "Luxury",
    tier: "Elite",
    name: "Elite Luxury Credit Card",
    description: "elite level luxury credit card product.",
    risk_customer: 7,
    value_customer: 10,
    profit_margin: 10,
    risk_bank: 3,
    retention_value: 10,
    details: {
      interest_rate: 14.99,
      annual_fee: 695,
      credit_limit: 100000,
      rewards_rate: 5.5,
    },
  },
  {
    product_id: "PROD_41",
    category: "Insurance",
    subcategory: "Home",
    tier: "Entry",
    name: "Entry Home Insurance",
    description: "entry level home insurance product.",
    risk_customer: 6,
    value_customer: 6,
    profit_margin: 5,
    risk_bank: 6,
    retention_value: 6,
    details: {
      monthly_premium: 25,
      deductible: 1000,
      coverage_amount: 100000,
    },
  },
  {
    product_id: "PROD_42",
    category: "Insurance",
    subcategory: "Home",
    tier: "Standard",
    name: "Standard Home Insurance",
    description: "standard level home insurance product.",
    risk_customer: 7,
    value_customer: 8,
    profit_margin: 6,
    risk_bank: 5,
    retention_value: 8,
    details: {
      monthly_premium: 50,
      deductible: 750,
      coverage_amount: 250000,
    },
  },
  {
    product_id: "PROD_43",
    category: "Insurance",
    subcategory: "Home",
    tier: "Premium",
    name: "Premium Home Insurance",
    description: "premium level home insurance product.",
    risk_customer: 8,
    value_customer: 10,
    profit_margin: 7,
    risk_bank: 4,
    retention_value: 10,
    details: {
      monthly_premium: 100,
      deductible: 500,
      coverage_amount: 500000,
    },
  },
  {
    product_id: "PROD_44",
    category: "Insurance",
    subcategory: "Home",
    tier: "Elite",
    name: "Elite Home Insurance",
    description: "elite level home insurance product.",
    risk_customer: 10,
    value_customer: 10,
    profit_margin: 8,
    risk_bank: 4,
    retention_value: 10,
    details: {
      monthly_premium: 150,
      deductible: 250,
      coverage_amount: 1000000,
    },
  },
  {
    product_id: "PROD_45",
    category: "Insurance",
    subcategory: "Health",
    tier: "Entry",
    name: "Entry Health Insurance",
    description: "entry level health insurance product.",
    risk_customer: 2,
    value_customer: 6,
    profit_margin: 5,
    risk_bank: 8,
    retention_value: 6,
    details: {
      monthly_premium: 100,
      deductible: 2000,
      coverage_amount: 500000,
    },
  },
  {
    product_id: "PROD_46",
    category: "Insurance",
    subcategory: "Health",
    tier: "Standard",
    name: "Standard Health Insurance",
    description: "standard level health insurance product.",
    risk_customer: 2,
    value_customer: 8,
    profit_margin: 6,
    risk_bank: 7,
    retention_value: 8,
    details: {
      monthly_premium: 250,
      deductible: 1500,
      coverage_amount: 1000000,
    },
  },
  {
    product_id: "PROD_47",
    category: "Insurance",
    subcategory: "Health",
    tier: "Premium",
    name: "Premium Health Insurance",
    description: "premium level health insurance product.",
    risk_customer: 2,
    value_customer: 10,
    profit_margin: 7,
    risk_bank: 6,
    retention_value: 10,
    details: {
      monthly_premium: 400,
      deductible: 1000,
      coverage_amount: 3000000,
    },
  },
  {
    product_id: "PROD_48",
    category: "Insurance",
    subcategory: "Health",
    tier: "Elite",
    name: "Elite Health Insurance",
    description: "elite level health insurance product.",
    risk_customer: 3,
    value_customer: 10,
    profit_margin: 8,
    risk_bank: 6,
    retention_value: 10,
    details: {
      monthly_premium: 600,
      deductible: 500,
      coverage_amount: 5000000,
    },
  },
  {
    product_id: "PROD_49",
    category: "Insurance",
    subcategory: "Life",
    tier: "Entry",
    name: "Entry Life Insurance",
    description: "entry level life insurance product.",
    risk_customer: 2,
    value_customer: 4,
    profit_margin: 6,
    risk_bank: 6,
    retention_value: 5,
    details: {
      monthly_premium: 20,
      deductible: 0,
      coverage_amount: 100000,
    },
  },
  {
    product_id: "PROD_50",
    category: "Insurance",
    subcategory: "Life",
    tier: "Standard",
    name: "Standard Life Insurance",
    description: "standard level life insurance product.",
    risk_customer: 2,
    value_customer: 6,
    profit_margin: 7,
    risk_bank: 5,
    retention_value: 7,
    details: {
      monthly_premium: 45,
      deductible: 0,
      coverage_amount: 250000,
    },
  },
  {
    product_id: "PROD_51",
    category: "Insurance",
    subcategory: "Life",
    tier: "Premium",
    name: "Premium Life Insurance",
    description: "premium level life insurance product.",
    risk_customer: 2,
    value_customer: 8,
    profit_margin: 8,
    risk_bank: 4,
    retention_value: 9,
    details: {
      monthly_premium: 95,
      deductible: 0,
      coverage_amount: 500000,
    },
  },
  {
    product_id: "PROD_52",
    category: "Insurance",
    subcategory: "Life",
    tier: "Elite",
    name: "Elite Life Insurance",
    description: "elite level life insurance product.",
    risk_customer: 3,
    value_customer: 10,
    profit_margin: 10,
    risk_bank: 4,
    retention_value: 10,
    details: {
      monthly_premium: 150,
      deductible: 0,
      coverage_amount: 1000000,
    },
  },
  {
    product_id: "PROD_53",
    category: "Insurance",
    subcategory: "Auto",
    tier: "Entry",
    name: "Entry Auto Insurance",
    description: "entry level auto insurance product.",
    risk_customer: 2,
    value_customer: 4,
    profit_margin: 5,
    risk_bank: 6,
    retention_value: 4,
    details: {
      monthly_premium: 50,
      deductible: 1000,
      coverage_amount: 50000,
    },
  },
  {
    product_id: "PROD_54",
    category: "Insurance",
    subcategory: "Auto",
    tier: "Standard",
    name: "Standard Auto Insurance",
    description: "standard level auto insurance product.",
    risk_customer: 3,
    value_customer: 6,
    profit_margin: 6,
    risk_bank: 5,
    retention_value: 5,
    details: {
      monthly_premium: 100,
      deductible: 750,
      coverage_amount: 100000,
    },
  },
  {
    product_id: "PROD_55",
    category: "Insurance",
    subcategory: "Auto",
    tier: "Premium",
    name: "Premium Auto Insurance",
    description: "premium level auto insurance product.",
    risk_customer: 4,
    value_customer: 8,
    profit_margin: 7,
    risk_bank: 4,
    retention_value: 6,
    details: {
      monthly_premium: 150,
      deductible: 500,
      coverage_amount: 250000,
    },
  },
  {
    product_id: "PROD_56",
    category: "Insurance",
    subcategory: "Auto",
    tier: "Elite",
    name: "Elite Auto Insurance",
    description: "elite level auto insurance product.",
    risk_customer: 4,
    value_customer: 10,
    profit_margin: 8,
    risk_bank: 4,
    retention_value: 8,
    details: {
      monthly_premium: 200,
      deductible: 250,
      coverage_amount: 500000,
    },
  },
  {
    product_id: "PROD_57",
    category: "Insurance",
    subcategory: "Travel",
    tier: "Entry",
    name: "Entry Travel Insurance",
    description: "entry level travel insurance product.",
    risk_customer: 3,
    value_customer: 4,
    profit_margin: 6,
    risk_bank: 4,
    retention_value: 2,
    details: {
      monthly_premium: 15,
      deductible: 250,
      coverage_amount: 25000,
    },
  },
  {
    product_id: "PROD_58",
    category: "Insurance",
    subcategory: "Travel",
    tier: "Standard",
    name: "Standard Travel Insurance",
    description: "standard level travel insurance product.",
    risk_customer: 4,
    value_customer: 5,
    profit_margin: 7,
    risk_bank: 3,
    retention_value: 3,
    details: {
      monthly_premium: 25,
      deductible: 150,
      coverage_amount: 50000,
    },
  },
  {
    product_id: "PROD_59",
    category: "Insurance",
    subcategory: "Travel",
    tier: "Premium",
    name: "Premium Travel Insurance",
    description: "premium level travel insurance product.",
    risk_customer: 5,
    value_customer: 6,
    profit_margin: 8,
    risk_bank: 3,
    retention_value: 4,
    details: {
      monthly_premium: 45,
      deductible: 100,
      coverage_amount: 100000,
    },
  },
  {
    product_id: "PROD_60",
    category: "Insurance",
    subcategory: "Travel",
    tier: "Elite",
    name: "Elite Travel Insurance",
    description: "elite level travel insurance product.",
    risk_customer: 6,
    value_customer: 8,
    profit_margin: 10,
    risk_bank: 2,
    retention_value: 5,
    details: {
      monthly_premium: 75,
      deductible: 50,
      coverage_amount: 250000,
    },
  },
  {
    product_id: "PROD_61",
    category: "Insurance",
    subcategory: "Pet",
    tier: "Entry",
    name: "Entry Pet Insurance",
    description: "entry level pet insurance product.",
    risk_customer: 2,
    value_customer: 4,
    profit_margin: 5,
    risk_bank: 4,
    retention_value: 3,
    details: {
      monthly_premium: 20,
      deductible: 500,
      coverage_amount: 5000,
    },
  },
  {
    product_id: "PROD_62",
    category: "Insurance",
    subcategory: "Pet",
    tier: "Standard",
    name: "Standard Pet Insurance",
    description: "standard level pet insurance product.",
    risk_customer: 3,
    value_customer: 5,
    profit_margin: 6,
    risk_bank: 3,
    retention_value: 4,
    details: {
      monthly_premium: 35,
      deductible: 350,
      coverage_amount: 10000,
    },
  },
  {
    product_id: "PROD_63",
    category: "Insurance",
    subcategory: "Pet",
    tier: "Premium",
    name: "Premium Pet Insurance",
    description: "premium level pet insurance product.",
    risk_customer: 4,
    value_customer: 6,
    profit_margin: 7,
    risk_bank: 3,
    retention_value: 5,
    details: {
      monthly_premium: 50,
      deductible: 250,
      coverage_amount: 15000,
    },
  },
  {
    product_id: "PROD_64",
    category: "Insurance",
    subcategory: "Pet",
    tier: "Elite",
    name: "Elite Pet Insurance",
    description: "elite level pet insurance product.",
    risk_customer: 4,
    value_customer: 8,
    profit_margin: 8,
    risk_bank: 2,
    retention_value: 6,
    details: {
      monthly_premium: 75,
      deductible: 100,
      coverage_amount: 25000,
    },
  },
  {
    product_id: "PROD_65",
    category: "Insurance",
    subcategory: "Business",
    tier: "Entry",
    name: "Entry Business Insurance",
    description: "entry level business insurance product.",
    risk_customer: 6,
    value_customer: 5,
    profit_margin: 6,
    risk_bank: 10,
    retention_value: 4,
    details: {
      monthly_premium: 100,
      deductible: 2000,
      coverage_amount: 250000,
    },
  },
  {
    product_id: "PROD_66",
    category: "Insurance",
    subcategory: "Business",
    tier: "Standard",
    name: "Standard Business Insurance",
    description: "standard level business insurance product.",
    risk_customer: 8,
    value_customer: 7,
    profit_margin: 8,
    risk_bank: 9,
    retention_value: 6,
    details: {
      monthly_premium: 250,
      deductible: 1500,
      coverage_amount: 500000,
    },
  },
  {
    product_id: "PROD_67",
    category: "Insurance",
    subcategory: "Business",
    tier: "Premium",
    name: "Premium Business Insurance",
    description: "premium level business insurance product.",
    risk_customer: 10,
    value_customer: 9,
    profit_margin: 10,
    risk_bank: 8,
    retention_value: 8,
    details: {
      monthly_premium: 500,
      deductible: 1000,
      coverage_amount: 1000000,
    },
  },
  {
    product_id: "PROD_68",
    category: "Insurance",
    subcategory: "Business",
    tier: "Elite",
    name: "Elite Business Insurance",
    description: "elite level business insurance product.",
    risk_customer: 10,
    value_customer: 10,
    profit_margin: 10,
    risk_bank: 7,
    retention_value: 10,
    details: {
      monthly_premium: 1000,
      deductible: 500,
      coverage_amount: 5000000,
    },
  },
  {
    product_id: "PROD_69",
    category: "Loan",
    subcategory: "Personal",
    tier: "Entry",
    name: "Entry Personal Loan",
    description: "entry level personal loan product.",
    risk_customer: 4,
    value_customer: 4,
    profit_margin: 6,
    risk_bank: 8,
    retention_value: 3,
    details: {
      interest_rate: 12.99,
      loan_amount: 5000,
      term_months: 24,
    },
  },
  {
    product_id: "PROD_70",
    category: "Loan",
    subcategory: "Personal",
    tier: "Standard",
    name: "Standard Personal Loan",
    description: "standard level personal loan product.",
    risk_customer: 5,
    value_customer: 6,
    profit_margin: 7,
    risk_bank: 7,
    retention_value: 4,
    details: {
      interest_rate: 10.99,
      loan_amount: 15000,
      term_months: 36,
    },
  },
  {
    product_id: "PROD_71",
    category: "Loan",
    subcategory: "Personal",
    tier: "Premium",
    name: "Premium Personal Loan",
    description: "premium level personal loan product.",
    risk_customer: 6,
    value_customer: 8,
    profit_margin: 8,
    risk_bank: 6,
    retention_value: 5,
    details: {
      interest_rate: 9.49,
      loan_amount: 30000,
      term_months: 48,
    },
  },
  {
    product_id: "PROD_72",
    category: "Loan",
    subcategory: "Personal",
    tier: "Elite",
    name: "Elite Personal Loan",
    description: "elite level personal loan product.",
    risk_customer: 7,
    value_customer: 10,
    profit_margin: 10,
    risk_bank: 6,
    retention_value: 6,
    details: {
      interest_rate: 7.99,
      loan_amount: 50000,
      term_months: 60,
    },
  },
  {
    product_id: "PROD_73",
    category: "Loan",
    subcategory: "Home",
    tier: "Entry",
    name: "Entry Home Loan",
    description: "entry level home loan product.",
    risk_customer: 6,
    value_customer: 6,
    profit_margin: 5,
    risk_bank: 6,
    retention_value: 6,
    details: {
      interest_rate: 6.99,
      loan_amount: 100000,
      term_months: 180,
    },
  },
  {
    product_id: "PROD_74",
    category: "Loan",
    subcategory: "Home",
    tier: "Standard",
    name: "Standard Home Loan",
    description: "standard level home loan product.",
    risk_customer: 7,
    value_customer: 8,
    profit_margin: 6,
    risk_bank: 5,
    retention_value: 8,
    details: {
      interest_rate: 5.99,
      loan_amount: 300000,
      term_months: 240,
    },
  },
  {
    product_id: "PROD_75",
    category: "Loan",
    subcategory: "Home",
    tier: "Premium",
    name: "Premium Home Loan",
    description: "premium level home loan product.",
    risk_customer: 8,
    value_customer: 10,
    profit_margin: 7,
    risk_bank: 4,
    retention_value: 10,
    details: {
      interest_rate: 4.99,
      loan_amount: 600000,
      term_months: 300,
    },
  },
  {
    product_id: "PROD_76",
    category: "Loan",
    subcategory: "Home",
    tier: "Elite",
    name: "Elite Home Loan",
    description: "elite level home loan product.",
    risk_customer: 10,
    value_customer: 10,
    profit_margin: 8,
    risk_bank: 4,
    retention_value: 10,
    details: {
      interest_rate: 3.99,
      loan_amount: 1000000,
      term_months: 360,
    },
  },
  {
    product_id: "PROD_77",
    category: "Loan",
    subcategory: "Vehicle",
    tier: "Entry",
    name: "Entry Vehicle Loan",
    description: "entry level vehicle loan product.",
    risk_customer: 4,
    value_customer: 4,
    profit_margin: 4,
    risk_bank: 5,
    retention_value: 4,
    details: {
      interest_rate: 7.99,
      loan_amount: 10000,
      term_months: 36,
    },
  },
  {
    product_id: "PROD_78",
    category: "Loan",
    subcategory: "Vehicle",
    tier: "Standard",
    name: "Standard Vehicle Loan",
    description: "standard level vehicle loan product.",
    risk_customer: 5,
    value_customer: 6,
    profit_margin: 5,
    risk_bank: 4,
    retention_value: 5,
    details: {
      interest_rate: 6.99,
      loan_amount: 25000,
      term_months: 48,
    },
  },
  {
    product_id: "PROD_79",
    category: "Loan",
    subcategory: "Vehicle",
    tier: "Premium",
    name: "Premium Vehicle Loan",
    description: "premium level vehicle loan product.",
    risk_customer: 6,
    value_customer: 8,
    profit_margin: 6,
    risk_bank: 4,
    retention_value: 6,
    details: {
      interest_rate: 5.99,
      loan_amount: 50000,
      term_months: 60,
    },
  },
  {
    product_id: "PROD_80",
    category: "Loan",
    subcategory: "Vehicle",
    tier: "Elite",
    name: "Elite Vehicle Loan",
    description: "elite level vehicle loan product.",
    risk_customer: 7,
    value_customer: 10,
    profit_margin: 7,
    risk_bank: 3,
    retention_value: 8,
    details: {
      interest_rate: 4.99,
      loan_amount: 100000,
      term_months: 72,
    },
  },
  {
    product_id: "PROD_81",
    category: "Loan",
    subcategory: "Education",
    tier: "Entry",
    name: "Entry Education Loan",
    description: "entry level education loan product.",
    risk_customer: 5,
    value_customer: 5,
    profit_margin: 3,
    risk_bank: 6,
    retention_value: 4,
    details: {
      interest_rate: 6.49,
      loan_amount: 10000,
      term_months: 60,
    },
  },
  {
    product_id: "PROD_82",
    category: "Loan",
    subcategory: "Education",
    tier: "Standard",
    name: "Standard Education Loan",
    description: "standard level education loan product.",
    risk_customer: 6,
    value_customer: 7,
    profit_margin: 4,
    risk_bank: 5,
    retention_value: 6,
    details: {
      interest_rate: 5.49,
      loan_amount: 25000,
      term_months: 120,
    },
  },
  {
    product_id: "PROD_83",
    category: "Loan",
    subcategory: "Education",
    tier: "Premium",
    name: "Premium Education Loan",
    description: "premium level education loan product.",
    risk_customer: 7,
    value_customer: 9,
    profit_margin: 5,
    risk_bank: 4,
    retention_value: 8,
    details: {
      interest_rate: 4.49,
      loan_amount: 50000,
      term_months: 180,
    },
  },
  {
    product_id: "PROD_84",
    category: "Loan",
    subcategory: "Education",
    tier: "Elite",
    name: "Elite Education Loan",
    description: "elite level education loan product.",
    risk_customer: 8,
    value_customer: 10,
    profit_margin: 6,
    risk_bank: 4,
    retention_value: 10,
    details: {
      interest_rate: 3.49,
      loan_amount: 100000,
      term_months: 240,
    },
  },
  {
    product_id: "PROD_85",
    category: "Loan",
    subcategory: "Business",
    tier: "Entry",
    name: "Entry Business Loan",
    description: "entry level business loan product.",
    risk_customer: 6,
    value_customer: 5,
    profit_margin: 6,
    risk_bank: 10,
    retention_value: 4,
    details: {
      interest_rate: 9.99,
      loan_amount: 25000,
      term_months: 36,
    },
  },
  {
    product_id: "PROD_86",
    category: "Loan",
    subcategory: "Business",
    tier: "Standard",
    name: "Standard Business Loan",
    description: "standard level business loan product.",
    risk_customer: 8,
    value_customer: 7,
    profit_margin: 8,
    risk_bank: 9,
    retention_value: 6,
    details: {
      interest_rate: 8.99,
      loan_amount: 100000,
      term_months: 60,
    },
  },
  {
    product_id: "PROD_87",
    category: "Loan",
    subcategory: "Business",
    tier: "Premium",
    name: "Premium Business Loan",
    description: "premium level business loan product.",
    risk_customer: 10,
    value_customer: 9,
    profit_margin: 10,
    risk_bank: 8,
    retention_value: 8,
    details: {
      interest_rate: 7.99,
      loan_amount: 250000,
      term_months: 84,
    },
  },
  {
    product_id: "PROD_88",
    category: "Loan",
    subcategory: "Business",
    tier: "Elite",
    name: "Elite Business Loan",
    description: "elite level business loan product.",
    risk_customer: 10,
    value_customer: 10,
    profit_margin: 10,
    risk_bank: 7,
    retention_value: 10,
    details: {
      interest_rate: 6.99,
      loan_amount: 500000,
      term_months: 120,
    },
  },
  {
    product_id: "PROD_89",
    category: "Investment",
    subcategory: "Mutual Fund",
    tier: "Entry",
    name: "Entry Mutual Fund Investment",
    description: "entry level mutual fund investment product.",
    risk_customer: 4,
    value_customer: 4,
    profit_margin: 4,
    risk_bank: 4,
    retention_value: 4,
    details: {
      min_investment: 1000,
      expected_annual_return: 6.0,
      volatility: 3,
    },
  },
  {
    product_id: "PROD_90",
    category: "Investment",
    subcategory: "Mutual Fund",
    tier: "Standard",
    name: "Standard Mutual Fund Investment",
    description: "standard level mutual fund investment product.",
    risk_customer: 5,
    value_customer: 6,
    profit_margin: 5,
    risk_bank: 3,
    retention_value: 6,
    details: {
      min_investment: 5000,
      expected_annual_return: 8.0,
      volatility: 4,
    },
  },
  {
    product_id: "PROD_91",
    category: "Investment",
    subcategory: "Mutual Fund",
    tier: "Premium",
    name: "Premium Mutual Fund Investment",
    description: "premium level mutual fund investment product.",
    risk_customer: 6,
    value_customer: 8,
    profit_margin: 6,
    risk_bank: 3,
    retention_value: 8,
    details: {
      min_investment: 10000,
      expected_annual_return: 10.0,
      volatility: 5,
    },
  },
  {
    product_id: "PROD_92",
    category: "Investment",
    subcategory: "Mutual Fund",
    tier: "Elite",
    name: "Elite Mutual Fund Investment",
    description: "elite level mutual fund investment product.",
    risk_customer: 7,
    value_customer: 10,
    profit_margin: 7,
    risk_bank: 2,
    retention_value: 10,
    details: {
      min_investment: 25000,
      expected_annual_return: 12.0,
      volatility: 6,
    },
  },
  {
    product_id: "PROD_93",
    category: "Investment",
    subcategory: "FD",
    tier: "Entry",
    name: "Entry FD Investment",
    description: "entry level fd investment product.",
    risk_customer: 1,
    value_customer: 3,
    profit_margin: 2,
    risk_bank: 1,
    retention_value: 4,
    details: {
      min_investment: 500,
      expected_annual_return: 2.0,
      volatility: 1,
    },
  },
  {
    product_id: "PROD_94",
    category: "Investment",
    subcategory: "FD",
    tier: "Standard",
    name: "Standard FD Investment",
    description: "standard level fd investment product.",
    risk_customer: 1,
    value_customer: 4,
    profit_margin: 3,
    risk_bank: 1,
    retention_value: 5,
    details: {
      min_investment: 2500,
      expected_annual_return: 2.5,
      volatility: 1,
    },
  },
  {
    product_id: "PROD_95",
    category: "Investment",
    subcategory: "FD",
    tier: "Premium",
    name: "Premium FD Investment",
    description: "premium level fd investment product.",
    risk_customer: 1,
    value_customer: 5,
    profit_margin: 4,
    risk_bank: 1,
    retention_value: 6,
    details: {
      min_investment: 10000,
      expected_annual_return: 3.0,
      volatility: 1,
    },
  },
  {
    product_id: "PROD_96",
    category: "Investment",
    subcategory: "FD",
    tier: "Elite",
    name: "Elite FD Investment",
    description: "elite level fd investment product.",
    risk_customer: 1,
    value_customer: 6,
    profit_margin: 4,
    risk_bank: 1,
    retention_value: 8,
    details: {
      min_investment: 25000,
      expected_annual_return: 3.5,
      volatility: 1,
    },
  },
  {
    product_id: "PROD_97",
    category: "Investment",
    subcategory: "Stocks",
    tier: "Entry",
    name: "Entry Stocks Investment",
    description: "entry level stocks investment product.",
    risk_customer: 6,
    value_customer: 5,
    profit_margin: 5,
    risk_bank: 5,
    retention_value: 4,
    details: {
      min_investment: 100,
      expected_annual_return: 7.0,
      volatility: 6,
    },
  },
  {
    product_id: "PROD_98",
    category: "Investment",
    subcategory: "Stocks",
    tier: "Standard",
    name: "Standard Stocks Investment",
    description: "standard level stocks investment product.",
    risk_customer: 8,
    value_customer: 7,
    profit_margin: 6,
    risk_bank: 4,
    retention_value: 6,
    details: {
      min_investment: 1000,
      expected_annual_return: 10.0,
      volatility: 7,
    },
  },
  {
    product_id: "PROD_99",
    category: "Investment",
    subcategory: "Stocks",
    tier: "Premium",
    name: "Premium Stocks Investment",
    description: "premium level stocks investment product.",
    risk_customer: 10,
    value_customer: 9,
    profit_margin: 7,
    risk_bank: 4,
    retention_value: 8,
    details: {
      min_investment: 5000,
      expected_annual_return: 12.0,
      volatility: 8,
    },
  },
  {
    product_id: "PROD_100",
    category: "Investment",
    subcategory: "Stocks",
    tier: "Elite",
    name: "Elite Stocks Investment",
    description: "elite level stocks investment product.",
    risk_customer: 10,
    value_customer: 10,
    profit_margin: 8,
    risk_bank: 3,
    retention_value: 10,
    details: {
      min_investment: 20000,
      expected_annual_return: 15.0,
      volatility: 9,
    },
  },
  {
    product_id: "PROD_101",
    category: "Investment",
    subcategory: "Gold",
    tier: "Entry",
    name: "Entry Gold Investment",
    description: "entry level gold investment product.",
    risk_customer: 2,
    value_customer: 4,
    profit_margin: 3,
    risk_bank: 2,
    retention_value: 4,
    details: {
      min_investment: 500,
      expected_annual_return: 3.0,
      volatility: 3,
    },
  },
  {
    product_id: "PROD_102",
    category: "Investment",
    subcategory: "Gold",
    tier: "Standard",
    name: "Standard Gold Investment",
    description: "standard level gold investment product.",
    risk_customer: 3,
    value_customer: 5,
    profit_margin: 4,
    risk_bank: 2,
    retention_value: 5,
    details: {
      min_investment: 2500,
      expected_annual_return: 4.0,
      volatility: 3,
    },
  },
  {
    product_id: "PROD_103",
    category: "Investment",
    subcategory: "Gold",
    tier: "Premium",
    name: "Premium Gold Investment",
    description: "premium level gold investment product.",
    risk_customer: 4,
    value_customer: 6,
    profit_margin: 5,
    risk_bank: 2,
    retention_value: 6,
    details: {
      min_investment: 10000,
      expected_annual_return: 5.0,
      volatility: 4,
    },
  },
  {
    product_id: "PROD_104",
    category: "Investment",
    subcategory: "Gold",
    tier: "Elite",
    name: "Elite Gold Investment",
    description: "elite level gold investment product.",
    risk_customer: 4,
    value_customer: 8,
    profit_margin: 6,
    risk_bank: 2,
    retention_value: 8,
    details: {
      min_investment: 25000,
      expected_annual_return: 6.0,
      volatility: 4,
    },
  },
  {
    product_id: "PROD_105",
    category: "Investment",
    subcategory: "Real Estate",
    tier: "Entry",
    name: "Entry Real Estate Investment",
    description: "entry level real estate investment product.",
    risk_customer: 6,
    value_customer: 5,
    profit_margin: 4,
    risk_bank: 5,
    retention_value: 5,
    details: {
      min_investment: 10000,
      expected_annual_return: 5.0,
      volatility: 2,
    },
  },
  {
    product_id: "PROD_106",
    category: "Investment",
    subcategory: "Real Estate",
    tier: "Standard",
    name: "Standard Real Estate Investment",
    description: "standard level real estate investment product.",
    risk_customer: 7,
    value_customer: 7,
    profit_margin: 5,
    risk_bank: 4,
    retention_value: 7,
    details: {
      min_investment: 50000,
      expected_annual_return: 7.0,
      volatility: 3,
    },
  },
  {
    product_id: "PROD_107",
    category: "Investment",
    subcategory: "Real Estate",
    tier: "Premium",
    name: "Premium Real Estate Investment",
    description: "premium level real estate investment product.",
    risk_customer: 8,
    value_customer: 9,
    profit_margin: 6,
    risk_bank: 4,
    retention_value: 9,
    details: {
      min_investment: 100000,
      expected_annual_return: 9.0,
      volatility: 4,
    },
  },
  {
    product_id: "PROD_108",
    category: "Investment",
    subcategory: "Real Estate",
    tier: "Elite",
    name: "Elite Real Estate Investment",
    description: "elite level real estate investment product.",
    risk_customer: 10,
    value_customer: 10,
    profit_margin: 7,
    risk_bank: 3,
    retention_value: 10,
    details: {
      min_investment: 250000,
      expected_annual_return: 12.0,
      volatility: 5,
    },
  },
];

export const getProduct = (productId: string) => FINANCIAL_PRODUCTS.filter((product) => product.product_id === productId)[0] ?? null;